import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import EmptyState from '@/Components/EmptyState';
import StatusBadge from '@/Components/StatusBadge';
import SummaryCard from '@/Components/SummaryCard';
import { Head, Link, router } from '@inertiajs/react';
import { useState } from 'react';

const moduleLabels = { leave: 'Cuti / Izin', travel: 'Perjalanan Dinas', settlement: 'Settlement', medical: 'Medical Claim' };
const money = (value) => value == null ? 'Terbatas' : new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(value);

export default function Index({ report = {}, filters = {}, statuses = [], canExport = false }) {
    const [values, setValues] = useState({ module: filters.module ?? '', status: filters.status ?? '', date_from: filters.date_from ?? '', date_to: filters.date_to ?? '' });
    const rows = report.data ?? [];
    const update = (key, value) => setValues((current) => ({ ...current, [key]: value }));
    const apply = (event) => { event.preventDefault(); router.get(route('reports.index'), Object.fromEntries(Object.entries(values).filter(([, value]) => value)), { preserveState: true, preserveScroll: true }); };
    const reset = () => { const empty = { module: '', status: '', date_from: '', date_to: '' }; setValues(empty); router.get(route('reports.index'), {}, { preserveState: true, replace: true }); };

    return <AuthenticatedLayout title="Laporan Transaksi" breadcrumbs={['Kendali', 'Laporan']}>
        <Head title="Laporan Transaksi" />
        <div className="mx-auto max-w-7xl space-y-5 px-4 py-7 sm:px-6 lg:px-8">
            <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.15em] text-blue-600">Kendali / Insight</p><h1 className="mt-1 text-2xl font-extrabold tracking-tight">Laporan Transaksi</h1><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Telusuri pengajuan berdasarkan modul, status, dan periode.</p></div>{canExport && <a href={route('reports.index', { ...filters, export: 1 })} className="ui-button-primary w-fit rounded-lg px-4 py-2.5 text-sm">Ekspor CSV</a>}</header>

            <section className="grid grid-cols-1 gap-3 sm:grid-cols-3"><SummaryCard title="Total transaksi" value={report.total ?? rows.length} subtitle="Sesuai filter dan hak akses" className="border-l-4 border-l-blue-600" /><SummaryCard title="Selesai" value={report.completed ?? 0} subtitle="Transaksi berstatus selesai" className="border-l-4 border-l-emerald-500" /><SummaryCard title="Nilai agregat" value={report.total_amount == null ? 'Terbatas' : money(report.total_amount)} subtitle={report.total_amount == null ? 'Nominal dibatasi sesuai hak akses' : 'Nilai transaksi sesuai filter'} className="border-l-4 border-l-amber-400" /></section>

            <section className="ui-card p-4 sm:p-5"><form onSubmit={apply} className="grid grid-cols-1 items-end gap-3 sm:grid-cols-2 lg:grid-cols-5"><label className="text-xs font-semibold text-slate-600 dark:text-slate-300">Modul<select aria-label="Filter modul" value={values.module} onChange={(event) => update('module', event.target.value)} className="mt-1 block w-full rounded-lg border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-900"><option value="">Semua modul</option>{Object.entries(moduleLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label className="text-xs font-semibold text-slate-600 dark:text-slate-300">Status<select aria-label="Filter status" value={values.status} onChange={(event) => update('status', event.target.value)} className="mt-1 block w-full rounded-lg border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-900"><option value="">Semua status</option>{statuses.map((status) => <option key={status} value={status}>{status.replaceAll('_', ' ')}</option>)}</select></label><label className="text-xs font-semibold text-slate-600 dark:text-slate-300">Dari tanggal<input aria-label="Tanggal mulai" type="date" value={values.date_from} onChange={(event) => update('date_from', event.target.value)} className="mt-1 block w-full rounded-lg border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-900" /></label><label className="text-xs font-semibold text-slate-600 dark:text-slate-300">Sampai tanggal<input aria-label="Tanggal akhir" type="date" value={values.date_to} onChange={(event) => update('date_to', event.target.value)} className="mt-1 block w-full rounded-lg border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-900" /></label><div className="flex gap-2"><button className="ui-button-primary rounded-lg px-4 py-2 text-sm">Terapkan</button><button type="button" onClick={reset} className="rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold dark:border-slate-700">Reset</button></div></form></section>

            <section className="ui-card overflow-hidden">{rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-50 text-[11px] font-bold uppercase tracking-wide text-slate-500 dark:bg-slate-900/70 dark:text-slate-400"><tr><th className="px-4 py-3">Dokumen</th><th className="px-4 py-3">Modul</th><th className="px-4 py-3">Tanggal</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Nilai</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{rows.map((row, index) => <tr key={`${row.module}-${row.id ?? row.document_number}-${index}`} className="hover:bg-slate-50/70 dark:hover:bg-slate-800/40"><td className="px-4 py-3 font-mono text-xs font-semibold">{row.document_number ?? '—'}</td><td className="px-4 py-3">{moduleLabels[row.module] ?? row.module}</td><td className="px-4 py-3">{row.date ? new Date(`${row.date}T00:00:00`).toLocaleDateString('id-ID') : '—'}</td><td className="px-4 py-3"><StatusBadge status={row.status} /></td><td className="px-4 py-3 text-right tabular-nums">{money(row.amount)}</td></tr>)}</tbody></table></div> : <div className="p-5"><EmptyState title="Tidak ada transaksi pada filter ini" description="Sesuaikan filter atau reset untuk melihat transaksi lainnya." /></div>}
                {(report?.links?.length ?? 0) > 3 && <nav aria-label="Navigasi laporan" className="flex items-center justify-between gap-3 border-t border-slate-200 px-4 py-3 text-xs dark:border-slate-700"><p className="text-slate-500">{report.from ?? 0}–{report.to ?? 0} dari {report.total ?? 0}</p><div className="flex gap-1">{report.links.map((page, index) => <Link key={`${page.label}-${index}`} href={page.url || '#'} preserveScroll className={`rounded-md border px-2.5 py-1.5 ${page.active ? 'border-blue-600 bg-blue-600 text-white' : 'border-slate-200 text-slate-600 dark:border-slate-700 dark:text-slate-300'} ${!page.url ? 'pointer-events-none opacity-40' : ''}`}>{page.label.replace('&laquo;', '‹').replace('&raquo;', '›')}</Link>)}</div></nav>}
            </section>
        </div>
    </AuthenticatedLayout>;
}
