import EmptyState from '@/Components/EmptyState';
import StatusBadge from '@/Components/StatusBadge';
import SummaryCard from '@/Components/SummaryCard';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, router } from '@inertiajs/react';
import { useState } from 'react';
import { formatRupiah, formatTanggal, labelStatus, statusValue } from './helpers';

export default function Index({ travels, filters, statuses }) {
    const [search, setSearch] = useState(filters?.search ?? '');
    const [status, setStatus] = useState(filters?.status ?? '');
    const rows = travels?.data ?? [];
    const apply = (event) => { event.preventDefault(); router.get(route('travels.index'), { search, status }, { preserveState: true, preserveScroll: true, replace: true }); };
    const reset = () => { setSearch(''); setStatus(''); router.get(route('travels.index'), {}, { preserveState: true, replace: true }); };
    const attention = rows.filter((row) => ['returned', 'submitted', 'in_review'].includes(statusValue(row.status))).length;
    const completed = rows.filter((row) => ['approved', 'advance_paid', 'completed'].includes(statusValue(row.status))).length;
    const pageAdvance = rows.reduce((sum, row) => sum + Number(row.total_advance || 0), 0);

    return <AuthenticatedLayout title="Perjalanan Dinas" breadcrumbs={[{ label: 'Dashboard', href: '/dashboard' }, { label: 'Perjalanan Dinas' }]}>
        <Head title="Perjalanan Dinas" />
        <div className="mx-auto max-w-7xl space-y-5 px-4 py-7 sm:px-6 lg:px-8">
            <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.15em] text-blue-600">Ruang Kerja / Perjalanan Dinas</p><h1 className="mt-1 text-2xl font-extrabold tracking-tight">Perjalanan Dinas</h1><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Kelola rute, biaya, advance, dan status perjalanan.</p></div><Link href={route('travels.create')} className="ui-button-primary w-fit rounded-lg px-4 py-2.5 text-sm">+ Buat perjalanan</Link></header>

            <section className="grid grid-cols-1 gap-3 sm:grid-cols-3"><SummaryCard judul="Total pengajuan" nilai={travels?.total ?? rows.length} sub="Sesuai filter" className="border-l-4 border-l-blue-600" /><SummaryCard judul="Advance (halaman ini)" nilai={formatRupiah(pageAdvance)} sub="Dihitung dari item biaya" className="border-l-4 border-l-emerald-500" /><SummaryCard judul="Perlu perhatian" nilai={attention} sub={`${completed} disetujui / selesai di halaman ini`} className="border-l-4 border-l-amber-400" /></section>

            <section className="ui-card overflow-hidden"><form onSubmit={apply} className="flex flex-col gap-3 border-b border-slate-200 p-4 sm:flex-row sm:items-end dark:border-slate-700"><div className="min-w-0 flex-1"><label className="text-xs font-semibold text-slate-600 dark:text-slate-300">Cari nomor atau keperluan</label><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Contoh: DINAS-202609-0001" className="mt-1 block w-full rounded-lg border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-900" /></div><div><label className="text-xs font-semibold text-slate-600 dark:text-slate-300">Status</label><select value={status} onChange={(event) => setStatus(event.target.value)} className="mt-1 block w-full rounded-lg border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-900"><option value="">Semua status</option>{(statuses ?? []).map((item) => <option key={item} value={item}>{labelStatus(item)}</option>)}</select></div><div className="flex gap-2"><button className="ui-button-primary rounded-lg px-4 py-2 text-sm">Terapkan</button><button type="button" onClick={reset} className="rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold dark:border-slate-700">Reset</button></div></form>
                {rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left text-sm"><thead className="bg-slate-50 text-[11px] font-bold uppercase tracking-wide text-slate-500 dark:bg-slate-900/70 dark:text-slate-400"><tr><th className="px-4 py-3">Nomor</th><th className="px-4 py-3">Keperluan / tujuan</th><th className="px-4 py-3">Periode</th><th className="px-4 py-3 text-right">Advance</th><th className="px-4 py-3">Status</th><th className="px-4 py-3" /></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{rows.map((row) => <tr key={row.id} className="hover:bg-slate-50/70 dark:hover:bg-slate-800/40"><td className="whitespace-nowrap px-4 py-3 font-mono text-xs font-bold">{row.request_number}</td><td className="max-w-sm px-4 py-3"><p className="line-clamp-2 font-medium">{row.purpose}</p><p className="mt-1 text-xs text-slate-500">{row.origin} → {row.destination}</p></td><td className="whitespace-nowrap px-4 py-3">{formatTanggal(row.start_date)} – {formatTanggal(row.end_date)}</td><td className="whitespace-nowrap px-4 py-3 text-right font-semibold tabular-nums">{formatRupiah(row.total_advance)}</td><td className="px-4 py-3"><StatusBadge status={statusValue(row.status)} /></td><td className="whitespace-nowrap px-4 py-3 text-right"><Link href={route('travels.show', row.id)} className="rounded-md px-2 py-1 text-xs font-bold text-blue-700 hover:bg-blue-50 dark:text-blue-400 dark:hover:bg-blue-950/50">Detail →</Link>{['draft', 'returned'].includes(statusValue(row.status)) && <Link href={route('travels.edit', row.id)} className="ml-2 rounded-md px-2 py-1 text-xs font-semibold text-slate-600 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-800">Ubah</Link>}</td></tr>)}</tbody></table></div> : <div className="p-5"><EmptyState title={search || status ? 'Perjalanan tidak ditemukan' : 'Belum ada perjalanan dinas'} description={search || status ? 'Ubah filter atau kata kunci pencarian.' : 'Buat pengajuan perjalanan dinas baru sebagai draf.'}><Link href={route('travels.create')} className="ui-button-primary rounded-lg px-4 py-2 text-sm">+ Buat perjalanan</Link></EmptyState></div>}
                {(travels?.links?.length ?? 0) > 3 && <nav aria-label="Navigasi perjalanan dinas" className="flex items-center justify-between gap-3 border-t border-slate-200 px-4 py-3 text-xs dark:border-slate-700"><p className="text-slate-500">{travels.from ?? 0}–{travels.to ?? 0} dari {travels.total ?? 0}</p><div className="flex gap-1">{travels.links.map((link, index) => <Link key={`${link.label}-${index}`} href={link.url ?? '#'} preserveState className={`rounded-md border px-2.5 py-1.5 ${link.active ? 'border-blue-600 bg-blue-600 text-white' : 'border-slate-200 text-slate-600 dark:border-slate-700 dark:text-slate-300'} ${!link.url ? 'pointer-events-none opacity-40' : ''}`}>{String(link.label).replace('&laquo;', '‹').replace('&raquo;', '›')}</Link>)}</div></nav>}
            </section>
        </div>
    </AuthenticatedLayout>;
}
