import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import Modal from '@/Components/Modal';
import StatusBadge from '@/Components/StatusBadge';
import SummaryCard from '@/Components/SummaryCard';
import { Head, Link, router } from '@inertiajs/react';
import { useState } from 'react';

const rupiah = (value) => `Rp ${Number(value ?? 0).toLocaleString('id-ID')}`;
const sourceLabels = { leave_request: 'Cuti / Izin', travel_request: 'Perjalanan Dinas', new_join: 'New Join', other: 'Lainnya' };
const differenceLabels = { overpayment: 'OVERPAYMENT', underpayment: 'UNDERPAYMENT', balanced: 'BALANCED' };
const differenceDescriptions = { overpayment: 'Advance lebih besar daripada realisasi biaya.', underpayment: 'Realisasi biaya lebih besar daripada advance.', balanced: 'Advance sama dengan realisasi biaya.' };
const differenceColors = { overpayment: 'border-amber-200 bg-amber-50 text-amber-900 dark:border-amber-900 dark:bg-amber-950/40 dark:text-amber-200', underpayment: 'border-blue-200 bg-blue-50 text-blue-900 dark:border-blue-900 dark:bg-blue-950/40 dark:text-blue-200', balanced: 'border-emerald-200 bg-emerald-50 text-emerald-900 dark:border-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-200' };

export default function Show({ settlement, source, difference, availableActions, timeline = [], attachments = [] }) {
    const [confirmAction, setConfirmAction] = useState(null);
    const post = (name) => router.post(route(`settlements.${name}`, settlement.id), {}, { preserveScroll: true, onSuccess: () => setConfirmAction(null) });
    const upload = (event) => {
        event.preventDefault();
        router.post(route('settlements.attachments.store', settlement.id), new FormData(event.currentTarget), { forceFormData: true, preserveScroll: true });
    };
    const statusSteps = ['draft', 'in_review', 'payment_processing', 'completed'];
    const activeStep = settlement.status === 'draft' || settlement.status === 'returned' ? 0 : settlement.status === 'completed' ? 3 : settlement.status === 'payment_processing' ? 2 : 1;
    const differenceType = difference.type ?? settlement.difference_type ?? 'balanced';

    return <AuthenticatedLayout title={settlement.settlement_number} breadcrumbs={['Settlement', settlement.settlement_number]}>
        <Head title={settlement.settlement_number} />
        <div className="mx-auto max-w-7xl space-y-5 px-4 py-7 sm:px-6 lg:px-8">
            <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-blue-600">Settlement / Detail</p><h1 className="mt-1 font-mono text-xl font-extrabold tracking-tight text-slate-900 dark:text-white">{settlement.settlement_number}</h1><div className="mt-2 flex items-center gap-2"><StatusBadge status={settlement.status} /><span className="text-xs text-slate-500">{sourceLabels[settlement.source_type] ?? settlement.source_type}</span></div></div><div className="flex flex-wrap gap-2">
                {availableActions.can_edit && <Link href={route('settlements.edit', settlement.id)} className="rounded-lg border border-slate-200 px-3 py-2 text-sm font-semibold hover:bg-slate-50 dark:border-slate-700 dark:hover:bg-slate-800">Ubah draft</Link>}
                {availableActions.can_submit && <button onClick={() => setConfirmAction('submit')} className="ui-button-primary rounded-lg px-4 py-2 text-sm">Ajukan review</button>}
                {availableActions.can_cancel && <button onClick={() => setConfirmAction('cancel')} className="rounded-lg border border-rose-200 px-3 py-2 text-sm font-semibold text-rose-700 hover:bg-rose-50 dark:border-rose-900 dark:text-rose-300 dark:hover:bg-rose-950/40">Batalkan</button>}
                {availableActions.can_complete && <button onClick={() => setConfirmAction('complete')} className="rounded-lg bg-emerald-600 px-3 py-2 text-sm font-semibold text-white hover:bg-emerald-700">Selesaikan pembayaran</button>}
            </div></header>

            <section className="ui-card p-5 sm:p-6"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.13em] text-blue-600">Progress</p><h2 className="mt-1 text-base font-bold">Alur settlement</h2></div><span className="text-xs text-slate-500">Nomor referensi: {settlement.source_reference || source?.request_number || '—'}</span></div><ol className="grid grid-cols-2 gap-3 md:grid-cols-4">{['Draf', 'Review HRGA & Finance', 'Proses pembayaran', 'Selesai'].map((step, index) => <li key={step} className={`rounded-xl border p-3 ${index <= activeStep ? 'border-blue-200 bg-blue-50/70 dark:border-blue-900 dark:bg-blue-950/30' : 'border-slate-200 dark:border-slate-700'}`}><span className={`inline-flex h-6 w-6 items-center justify-center rounded-full text-xs font-bold ${index <= activeStep ? 'bg-blue-600 text-white' : 'bg-slate-100 text-slate-500 dark:bg-slate-800'}`}>{index < activeStep ? '✓' : index + 1}</span><p className="mt-2 text-xs font-semibold">{step}</p></li>)}</ol></section>

            <section className={`rounded-2xl border p-5 sm:p-6 ${differenceColors[differenceType] ?? differenceColors.balanced}`}><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-xs font-extrabold tracking-[0.14em]">HASIL REKONSILIASI</p><h2 className="mt-1 text-xl font-extrabold">{differenceLabels[differenceType] ?? differenceType}</h2><p className="mt-1 text-sm opacity-80">{differenceDescriptions[differenceType] ?? 'Selisih dihitung ulang oleh server saat transaksi diproses.'}</p></div><p className="text-2xl font-extrabold tabular-nums">{rupiah(Math.abs(Number(difference.difference ?? 0)))}</p></div></section>

            <section className="grid grid-cols-1 gap-3 sm:grid-cols-3"><SummaryCard title="Advance" value={rupiah(difference.advance)} subtitle={['new_join', 'other'].includes(settlement.source_type) ? 'Sumber manual: advance Rp0' : 'Nilai dari pengajuan sumber'} /><SummaryCard title="Realisasi" value={rupiah(difference.actual)} subtitle="Jumlah item biaya aktual" /><SummaryCard title="Selisih" value={rupiah(Math.abs(Number(difference.difference ?? 0)))} subtitle={differenceLabels[differenceType] ?? differenceType} /></section>

            <section className="grid grid-cols-1 gap-5 lg:grid-cols-3"><article className="ui-card p-5 lg:col-span-2"><div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.13em] text-blue-600">Sumber</p><h2 className="mt-1 text-base font-bold">Referensi dan rincian biaya</h2></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600 dark:bg-slate-800 dark:text-slate-300">{sourceLabels[settlement.source_type] ?? settlement.source_type}</span></div><div className="mb-4 grid gap-3 rounded-xl bg-slate-50 p-4 dark:bg-slate-900 sm:grid-cols-2"><div><p className="text-xs text-slate-500">Nomor referensi sumber</p><p className="mt-1 text-sm font-bold">{settlement.source_reference || source?.request_number || '—'}</p></div><div><p className="text-xs text-slate-500">Karyawan</p><p className="mt-1 text-sm font-bold">{settlement.employee?.name || '—'} <span className="font-normal text-slate-500">{settlement.employee?.employee_number ? `· ${settlement.employee.employee_number}` : ''}</span></p></div>{source?.purpose && <div className="sm:col-span-2"><p className="text-xs text-slate-500">Keperluan / alasan sumber</p><p className="mt-1 text-sm">{source.purpose || source.reason}</p></div>}</div><div className="overflow-x-auto"><table className="w-full min-w-[500px] text-left text-sm"><thead className="text-xs uppercase tracking-wide text-slate-500"><tr><th className="py-2">Tanggal / deskripsi</th><th className="py-2">Kategori</th><th className="py-2 text-right">Nominal</th></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{settlement.items?.map((item) => <tr key={item.id}><td className="py-3"><p className="font-semibold">{item.description}</p><p className="mt-0.5 text-xs text-slate-500">{item.transaction_date}{item.receipt_no ? ` · Nota ${item.receipt_no}` : ''}</p></td><td className="py-3 capitalize">{item.category}</td><td className="py-3 text-right font-semibold tabular-nums">{rupiah(item.amount)}</td></tr>)}</tbody></table></div></article>

                <aside className="space-y-5"><section className="ui-card p-5"><h2 className="text-base font-bold">Bukti biaya</h2>{availableActions.can_upload && <form onSubmit={upload} className="mt-4 space-y-3"><input required type="file" name="file" accept=".pdf,.jpg,.jpeg,.png,.webp" className="block w-full text-xs text-slate-600 file:mr-3 file:rounded-md file:border-0 file:bg-slate-100 file:px-3 file:py-2 file:text-xs file:font-semibold dark:text-slate-300 dark:file:bg-slate-800" /><select name="document_type" defaultValue="receipt" className="block w-full rounded-lg border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-900"><option value="receipt">Nota</option><option value="supporting_document">Dokumen pendukung</option></select><button className="ui-button-primary rounded-lg px-3 py-2 text-sm">Unggah bukti</button></form>}<ul className="mt-4 space-y-2 text-sm">{attachments.map((attachment) => <li key={attachment.id} className="rounded-lg border border-slate-200 p-3 dark:border-slate-700"><a className="font-semibold text-blue-700 hover:underline dark:text-blue-400" href={attachment.download_url}>{attachment.original_name}</a><p className="mt-1 text-xs text-slate-500">{attachment.document_type} · {Math.ceil(attachment.file_size / 1024)} KB</p></li>)}{attachments.length === 0 && <li className="text-xs text-slate-500">Belum ada bukti terlampir.</li>}</ul></section>
                    <section className="ui-card p-5"><h2 className="text-base font-bold">Riwayat aktivitas</h2>{timeline.length ? <ol className="mt-4 space-y-4">{timeline.map((entry, index) => <li key={`${entry.at}-${index}`} className="relative border-l-2 border-blue-100 pl-4 dark:border-slate-700"><span className="absolute -left-[5px] top-1 h-2 w-2 rounded-full bg-blue-600" /><p className="text-sm font-semibold">{entry.action}</p><p className="mt-1 text-xs text-slate-500">{entry.actor?.name || 'Sistem'} · {entry.at ? new Date(entry.at).toLocaleString('id-ID') : '—'}</p>{entry.comments && <p className="mt-2 rounded-lg bg-slate-50 p-2 text-xs dark:bg-slate-900">{entry.comments}</p>}</li>)}</ol> : <p className="mt-3 text-sm text-slate-500">Belum ada aktivitas.</p>}</section></aside></section>
        </div>
        <Modal show={Boolean(confirmAction)} onClose={() => setConfirmAction(null)} maxWidth="md"><div className="p-6"><h2 className="text-lg font-bold text-slate-900 dark:text-white">{confirmAction === 'submit' ? 'Ajukan settlement?' : confirmAction === 'complete' ? 'Selesaikan pembayaran?' : 'Batalkan settlement?'}</h2><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{confirmAction === 'submit' ? 'Settlement akan diteruskan ke review sesuai workflow.' : confirmAction === 'complete' ? 'Pastikan pembayaran atau penyesuaian telah dilakukan.' : 'Settlement akan ditandai dibatalkan dan tidak dihapus dari riwayat.'}</p><div className="mt-5 flex justify-end gap-2"><button type="button" onClick={() => setConfirmAction(null)} className="rounded-lg border border-slate-200 px-4 py-2 text-sm font-semibold dark:border-slate-700">Kembali</button><button type="button" onClick={() => post(confirmAction)} className={`rounded-lg px-4 py-2 text-sm font-semibold text-white ${confirmAction === 'cancel' ? 'bg-rose-600 hover:bg-rose-700' : 'bg-blue-600 hover:bg-blue-700'}`}>Konfirmasi</button></div></div></Modal>
    </AuthenticatedLayout>;
}
