import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import EmptyState from '@/Components/EmptyState';
import { Head, Link, router, usePage } from '@inertiajs/react';
import { useState } from 'react';

export default function Index({ employees, filters }) {
    const { flash, import_result: importResult, auth } = usePage().props;
    const [search, setSearch] = useState(filters?.search ?? '');
    const [active, setActive] = useState(filters?.active ?? 'all');
    const canCreate = auth?.user?.permissions?.includes('employee.manage') ?? false;
    const rows = employees?.data ?? [];
    const applyFilter = (event) => { event.preventDefault(); router.get(route('master.employees.index'), { search, active }, { preserveState: true, preserveScroll: true }); };

    return <AuthenticatedLayout title="Master Karyawan" breadcrumbs={['Administrasi', 'Master Data', 'Karyawan']}>
        <Head title="Master Karyawan" />
        <div className="mx-auto max-w-7xl space-y-5 px-4 py-7 sm:px-6 lg:px-8">
            <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.15em] text-blue-600">Administrasi / Master Data</p><h1 className="mt-1 text-2xl font-extrabold tracking-tight">Karyawan</h1><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">Data profil ini menjadi sumber lookup dan snapshot pada pengajuan.</p></div>{canCreate && <Link href={route('master.employees.create')} className="ui-button-primary w-fit rounded-lg px-4 py-2.5 text-sm">+ Tambah karyawan</Link>}</header>

            {flash?.success && <div role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800 dark:border-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-200">{flash.success}</div>}
            {importResult && <section className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-900 dark:border-blue-900 dark:bg-blue-950/30 dark:text-blue-100"><p className="font-bold">Import selesai: {importResult.imported} berhasil, {importResult.failed.length} gagal.</p>{importResult.failed.length > 0 && <ul className="mt-2 list-disc space-y-1 pl-5 text-xs">{importResult.failed.slice(0, 10).map((failure, index) => <li key={index}>Baris {failure.row} ({failure.employee_number ?? '—'}): {failure.errors}</li>)}</ul>}</section>}

            <section className="grid grid-cols-1 gap-3 sm:grid-cols-3"><article className="ui-card border-l-4 border-l-blue-600 p-4"><p className="text-xs font-medium text-slate-500">Karyawan ditemukan</p><p className="mt-1 text-2xl font-extrabold">{employees?.total ?? rows.length}</p><p className="mt-1 text-xs text-slate-500">Sesuai filter dan akses</p></article><article className="ui-card border-l-4 border-l-emerald-500 p-4"><p className="text-xs font-medium text-slate-500">Baris halaman aktif</p><p className="mt-1 text-2xl font-extrabold">{rows.length}</p><p className="mt-1 text-xs text-slate-500">Data master yang ditampilkan</p></article><article className="ui-card border-l-4 border-l-amber-400 p-4"><p className="text-xs font-medium text-slate-500">Kolom lookup</p><p className="mt-1 text-sm font-bold">NIK · POH · Roster · Atasan</p><p className="mt-1 text-xs text-slate-500">Digunakan pada formulir transaksi</p></article></section>

            <section className="ui-card overflow-hidden"><form onSubmit={applyFilter} className="flex flex-col gap-3 border-b border-slate-200 p-4 sm:flex-row sm:items-end dark:border-slate-700"><div className="min-w-0 flex-1"><label className="text-xs font-semibold text-slate-600 dark:text-slate-300">Cari NIK, nama, atau departemen</label><input value={search} onChange={(event) => setSearch(event.target.value)} className="mt-1 block w-full rounded-lg border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-900" placeholder="Contoh: BP-001 / Budi / HRGA" /></div><div><label className="text-xs font-semibold text-slate-600 dark:text-slate-300">Status</label><select value={active} onChange={(event) => setActive(event.target.value)} className="mt-1 block w-full rounded-lg border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-900"><option value="all">Semua</option><option value="1">Aktif</option><option value="0">Nonaktif</option></select></div><button className="ui-button-primary rounded-lg px-4 py-2 text-sm">Terapkan</button></form>
                {rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-slate-50 text-[11px] font-bold uppercase tracking-wide text-slate-500 dark:bg-slate-900/70 dark:text-slate-400"><tr><th className="px-4 py-3">NIK / karyawan</th><th className="px-4 py-3">Departemen</th><th className="px-4 py-3">Jabatan</th><th className="px-4 py-3">POH / roster</th><th className="px-4 py-3">Status</th><th className="px-4 py-3" /></tr></thead><tbody className="divide-y divide-slate-100 dark:divide-slate-800">{rows.map((employee) => <tr key={employee.id} className="hover:bg-slate-50/70 dark:hover:bg-slate-800/40"><td className="px-4 py-3"><p className="font-mono text-xs font-bold">{employee.employee_number}</p><p className="mt-1 font-semibold">{employee.name}</p></td><td className="px-4 py-3">{employee.department ?? '—'}</td><td className="px-4 py-3">{employee.job_title ?? '—'}</td><td className="px-4 py-3"><p>{employee.poh_status === 'local' ? 'Lokal' : 'Non-lokal'}</p><p className="mt-1 text-xs text-slate-500">{employee.roster ?? 'Roster —'}</p></td><td className="px-4 py-3"><span className={`ui-badge ${employee.active ? 'bg-emerald-50 text-emerald-800 dark:bg-emerald-950/40 dark:text-emerald-300' : 'bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300'}`}>{employee.active ? 'Aktif' : 'Nonaktif'}</span></td><td className="px-4 py-3 text-right"><Link href={route('master.employees.show', employee.id)} className="rounded-md px-2 py-1 text-xs font-bold text-blue-700 hover:bg-blue-50 dark:text-blue-400 dark:hover:bg-blue-950/50">Detail →</Link></td></tr>)}</tbody></table></div> : <div className="p-5"><EmptyState title={search || active !== 'all' ? 'Karyawan tidak ditemukan' : 'Belum ada data karyawan'} description={search || active !== 'all' ? 'Ubah kata kunci atau filter status.' : 'Tambahkan atau import master karyawan agar formulir dapat mengambil profil dan relasi atasan.'}>{canCreate && !search && <Link href={route('master.employees.create')} className="ui-button-primary rounded-lg px-4 py-2 text-sm">Tambah karyawan</Link>}</EmptyState></div>}
                {(employees?.links?.length ?? 0) > 3 && <nav aria-label="Navigasi karyawan" className="flex items-center justify-between gap-3 border-t border-slate-200 px-4 py-3 text-xs dark:border-slate-700"><p className="text-slate-500">{employees.from ?? 0}–{employees.to ?? 0} dari {employees.total ?? 0}</p><div className="flex gap-1">{employees.links.map((page, index) => <Link key={`${page.label}-${index}`} href={page.url || '#'} preserveScroll className={`rounded-md border px-2.5 py-1.5 ${page.active ? 'border-blue-600 bg-blue-600 text-white' : 'border-slate-200 text-slate-600 dark:border-slate-700 dark:text-slate-300'} ${!page.url ? 'pointer-events-none opacity-40' : ''}`}>{page.label.replace('&laquo;', '‹').replace('&raquo;', '›')}</Link>)}</div></nav>}
            </section>
        </div>
    </AuthenticatedLayout>;
}
